FROM mcr.microsoft.com/playwright:v1.55.1-noble

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y fd-find gh less nginx ripgrep screen unzip zsh && \
    apt-get clean

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN npm install markdownlint-cli2 --global

RUN curl -sfLO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz && \
    tar -C /opt -xzf nvim-linux-x86_64.tar.gz && \
    ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin && \
    rm nvim-linux-x86_64.tar.gz

WORKDIR /root

# lazyvim

RUN git clone https://github.com/LazyVim/starter .config/nvim

COPY ./devcontainer/overrides/.config/nvim/lazyvim.json ./.config/nvim/

RUN echo 'vim.o.shell = "zsh"' >> .config/nvim/lua/config/options.lua

RUN nvim --headless "+Lazy! sync" +qa

#

COPY ./devcontainer/overrides/.ssh/known_hosts ./.ssh/

COPY ./devcontainer/overrides/.oh-my-zsh/custom/omz.zsh .oh-my-zsh/custom/

COPY ./devcontainer/overrides/sites/* /etc/nginx/sites-enabled/

COPY ./devcontainer/overrides/html/* /usr/share/nginx/html/

COPY ./devcontainer/run.after /usr/local/bin/

CMD run.after && exec sh -c 'trap : TERM INT; sleep infinity & wait'
