#!/usr/bin/env zsh

tag=logbook-devcontainer

if [ ! -f devcontainer/cidfile ] ; then
  echo cidfile does not exist
  exit 1
fi

podman exec \
  --cidfile devcontainer/cidfile \
  --interactive \
  --tty \
  $@
