#!/usr/bin/env zsh

tag=logbook-devcontainer

if [ -f devcontainer/cidfile ] ; then
  echo cidfile exists
  exit 1
fi

podman build -t $tag .

if [ "$SSH_AUTH_SOCK" = "" ]; then
  eval $(ssh-agent)
  ssh-add
fi

podman run \
  --cidfile devcontainer/cidfile \
  --detach \
  --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
  --publish 8080:8080 \
  --volume .:/root/logbook \
  --volume $HOME/.gitconfig:/root/.gitconfig.host:ro \
  --volume $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
  $tag
